### ISSUE TITLE
Cookies, Layout handles

### ISSUE THREAD

**Issue by jensvandorpe** [EcomDev/EcomDev_Varnish#11]
Hi Ivan,

To get the correct block as a response in the ajax calls you need to define your block in the <default> layout handle, otherwise you get an empty response. Is there a way to make this work with blocks that are not included in every page?

Is it correct that in order to make an element dynamic on a cached page you to create your own cookie in custom code and change the value of it everytime you change the content of you dynamic block?

Thanks in advance

Jens

**Comment by IvanChepurnyi** [comment]
In the end, the will be no page based AJAX requests in the default integration, as it is impossible to emulate full stack of the page automagically, without implementing performance inefficient responsers. 

I advice better to create instead your own ajax callable url with particular data scope you need for a customer, that will return cachable HTML content.
