### ISSUE TITLE
Unable to add cached product to cart from different browser

### ISSUE THREAD

**Issue by toonvd** [EcomDev/EcomDev_Varnish#14]
How to reproduce:

Use browser a, go to a product detail page, put it in cart (make sure its in cache).
Use browser b, go to a product detail page, put the same product in cart, result: empty shopping cart.

Has no effect on configurable products.

**Comment by IvanChepurnyi** [comment]
This is now solved via special token implementation in the module. See ecomdev/varnish/js/token.phtml template and EcomDev.Varnish.Token javascript details for hints on its implementation.

It works now in such a way, if it finds at least one input element with "form_key" name on the page, it will request it via ajax, by using ESI signature as token checksum salt. And later on it will automagically replace form key value in session on predispatch and will regenate a token with checksum, so you'll be able to post the data later on as well. Simple, secure and session free implementation, as token purely stored in cookie and then posted via form.

There is still a small drawback, as on some forms, form key is in **form** action attribute, so it makes things harder, and just requires from you some adjustement in theme.
