### ISSUE TITLE
Http ajax call blocked on Https pages

### ISSUE THREAD

**Issue by jensvandorpe** [EcomDev/EcomDev_Varnish#17]
Ivan,

To get the url for the ajax calls you use the getAjaxReloadUrl function, but this function only returns the path (via the parse_url function). As a result the call is blocked on https pages.
What is the reason you don't use the full url?

Could I just replace this the following or would this cause problems in other parts of the module?

$this->_ajaxReloadUrl = $this->_getUrl('varnish/ajax/reload',array("_secure" => Mage::app()->getStore()->isCurrentlySecure()));

Thanks in advance.

**Comment by IvanChepurnyi** [comment]
Fixed in alpha1 release
