### ISSUE TITLE
How to use Dynamic blocks with ajax?

### ISSUE THREAD

**Issue by hugoleodev** [EcomDev/EcomDev_Varnish#19]
Hi,

I would like to know, how can I implement on layout the dynamic block with ajax?

**Comment by toonvd** [comment]
It is explained here:
http://www.slideshare.net/ivanchepurnyi/advanced-varnishusage

**Comment by hugoleodev** [comment]
Is there any other detailed documentation?

**Comment by toonvd** [comment]
It can't be more detailed than in the slides over there, he explains the placeholders and everything...

**Comment by IvanChepurnyi** [comment]
I created a new folder in repo, called docs, fill free to create pull requests with such a documentaion ;)
