### ISSUE TITLE
When the session expires, all session related dynamic elements should be invalidated.

### ISSUE THREAD

**Issue by toonvd** [EcomDev/EcomDev_Varnish#20]
Hi @IvanChepurnyi,

Just found a bug in the extension, when the session expires, my top cart does not get refreshed, this is because the quote checksum cookie remains the same.

I fixed this by checking if a frontend cookie exists from my own file in the validate function like this:
```javascript
EcomDev.Varnish.AjaxBlock.addMethods({
    validate: function () {
        if (!this.config.cookie) {
            return true;
        }

        var currentValue = this.getCookieValue();

        if (currentValue === false && !this.storage.getValue('cookie')) {
            return true;
        }
        if(Mage.Cookies.get("frontend") === null){
            return false;
        }
        return this.storage.getValue('cookie') === currentValue;
}
```
If you approve of this, I could make a pullrequest.

**Comment by IvanChepurnyi** [comment]
I think we need a smarter solution, as session cookie name can be different for different projects. What I am thinking about is to create a possiblity to add additional dirty flag checks, like multiple cookies to control the dynamic block behaviour, as I exprience sometimes website that have different currencies and languages over the same url, so shopping cart can be different when user changes those values, so I want to add those smart checks.

**Comment by IvanChepurnyi** [comment]
Added a new set of parameters and rules for Ajax Blocks. Now you can call `setAdditionalCookie()` on ajax block, so it will additionally check existance of additional cookie tags, like for cart, there can be invalidation based on customer segment checksum, as customer might get logged out. 

Also there was a bug with checks on empty values of cookie, so now functionality works as expected. Let me know if you still experience such issues with `develop` branch.
