### ISSUE TITLE
HTTP Referer goes to holepunch ajaxcall after cart row delete in certain situations.

### ISSUE THREAD

**Issue by toonvd** [EcomDev/EcomDev_Varnish#22]
When you delete something in cart, Magento uses http_referer.
When you add something to the cart before it, the last url hit was the holepunch url, this means that the http_referer is this ajax call url. This gives a blank page.

**Comment by dng-dev** [comment]
You can fix it in the VCL simply overwrite the referer if its an esi call

**Comment by toonvd** [comment]
@dng-dev, does it also work with an Ajax call? Thx for the tip!

**Comment by dng-dev** [comment]
@toonvd try and error with xdebug and check the headers

**Comment by IvanChepurnyi** [comment]
Added possiblity to filter refferers in ESI include, see updated Esi block.
