### ISSUE TITLE
When a user logs in or adds something to cart, he gets a separate cache.

### ISSUE THREAD

**Issue by toonvd** [EcomDev/EcomDev_Varnish#23]
I believe this might be the difference between users with a PHP session and users without a PHP session.

**Comment by IvanChepurnyi** [comment]
You need to use ESI blocks for including shopping cart in this case. It is possible issue with you don't use placeholders for non logged in users. The bast way to use shopping cart as placeholder html (core/template) on page level and only on AJAX call to have a full functional cart block with session data.

**Comment by IvanChepurnyi** [comment]
Also I recommend filtering cookies for ESI block, there is such a possiblity for ESI blocks, just call setCookies(0) on block creation, so it will add /filter_cookies/1/ to url so VCL will remove any COOKIE requests for included block.
