### ISSUE TITLE
Connect to varnish (help wanted)

### ISSUE THREAD

**Issue by EugenPetrov** [EcomDev/EcomDev_Varnish#25]
Please help to connect your module to varnish. I am noob with varnish.

My environment is vagrant with ubuntu 14, nginx, varnish (version 3), magento 1.14.

- I installed module using the composer;
- configured varnish settings: inserted the secret key and enabled the debug;
- generated my default.vcl using shell ecomdev-varnish.php, the vcl:generate action.

And what shell I do next?

I tried to apply my default.vcl by varnishadm commands:
`varnishadm -T 127.0.0.1:6082 -S /etc/varnish/secret vcl.load {config_name} default.vcl`
`varnishadm -T 127.0.0.1:6082 -S /etc/varnish/secret vcl.use {config_name}`

But it is obviously not enough.

Please, say what I am missing. Many thanks!

**Comment by IvanChepurnyi** [comment]
Hi Eugen, 

Please post questions with help of configuration on http://magento.stackexchange.com/.
